"""
Tile the rendered frames into one sprite sheet for the web.

Run after a sprite render, passing the frames directory name:
    python3 scripts/blender/make-sprite-sheet.py _deskframes   # desk.py
    python3 scripts/blender/make-sprite-sheet.py               # asteroid.py

Two things matter for the browser here. The sheet is cropped to the union of
every frame's alpha bounding box, not to the render size — the subject never
fills the frame, and shipping that empty margin 36 times over is pure weight.
And the grid is written out alongside the image, because the component needs
the exact cell size to step background-position without drift.
"""

import json
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FRAMES = os.path.join(ROOT, "public", "asteroid",
                      sys.argv[1] if len(sys.argv) > 1 else "_frames")
OUT_IMG = os.path.join(ROOT, "public", "asteroid", "asteroid-sprite.webp")
OUT_META = os.path.join(ROOT, "src", "components", "site", "asteroidSprite.ts")
QUALITY = 82


def main():
    names = sorted(n for n in os.listdir(FRAMES) if n.endswith(".png"))
    if not names:
        sys.exit(f"no frames in {FRAMES} — run asteroid.py --mode sprite first")

    frames = [Image.open(os.path.join(FRAMES, n)).convert("RGBA") for n in names]

    # Union of every frame's alpha bbox. Per-frame cropping would make the
    # subject jitter between cells; one shared box keeps it registered.
    box = None
    for im in frames:
        b = im.getchannel("A").getbbox()
        if b is None:
            continue
        box = b if box is None else (min(box[0], b[0]), min(box[1], b[1]),
                                     max(box[2], b[2]), max(box[3], b[3]))
    if box is None:
        sys.exit("every frame is fully transparent")

    frames = [im.crop(box) for im in frames]
    cw, ch = frames[0].size

    # Keep the sheet close to square: a very wide or very tall atlas wastes
    # more padding and some GPUs cap texture dimensions around 8192px.
    import math as _m
    cols = min(8, max(1, int(_m.ceil(_m.sqrt(len(frames) * ch / cw)))))
    rows = (len(frames) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols * cw, rows * ch), (0, 0, 0, 0))
    for i, im in enumerate(frames):
        sheet.paste(im, ((i % cols) * cw, (i // cols) * ch))

    if max(sheet.size) > 8192:
        sys.exit(f"sheet {sheet.size} exceeds the 8192px texture limit — "
                 "render fewer frames or a smaller --res")
    sheet.save(OUT_IMG, "WEBP", quality=QUALITY, method=6)
    size_kb = os.path.getsize(OUT_IMG) / 1024

    meta = {"frames": len(frames), "cols": cols, "rows": rows,
            "cellW": cw, "cellH": ch,
            "sheetW": cols * cw, "sheetH": rows * ch}
    with open(OUT_META, "w") as fh:
        fh.write("// Generated by scripts/blender/make-sprite-sheet.py — do not edit.\n")
        fh.write("// Regenerate after re-rendering the Blender frames.\n")
        fh.write(f"export const ASTEROID_SPRITE = {json.dumps(meta, indent=2)} as const;\n")

    print(f"[sheet] {len(frames)} frames, cell {cw}x{ch}, "
          f"sheet {cols * cw}x{rows * ch}, {size_kb:.0f}KB")
    print(f"[sheet] wrote {OUT_IMG}")
    print(f"[sheet] wrote {OUT_META}")


if __name__ == "__main__":
    main()
