import type { Project } from "@/components/site/ProjectCard";
import { slugify } from "@/lib/utils";

export const SEED_PROJECTS: Project[] = [
  {
    id: "9",
    name: "Incident Diagnosis Engine (Replay)",
    description:
      "A Java 25 / Spring Boot service that diagnoses why a production service broke: it walks the trace-derived service dependency graph to find what the failure could have touched, detects when it started (CUSUM change-point), ranks suspect change events against that moment, then returns a ranked cause where every claim cites a real telemetry signal.",
    github_url: "https://github.com/Sashreek007/Replay",
    demo_url: null,
    image_url: "/projects/replay/walkthrough-poster.jpg",
    video_url: "/projects/replay/walkthrough.mp4",
    gallery: [
      {
        url: "/projects/replay/architecture.webp",
        caption: "System architecture",
        alt: "Pipeline diagram. An alert webhook is accepted with a 202 and the pipeline runs off-thread. Telemetry from Prometheus, Tempo and Loki stays inside the user's network. Four deterministic stages run with no model involved — Narrow (trace spans to a BFS radius), When (CUSUM change point), Suspects (causal window and score) and Gather (templating and budget, 2,000 lines down to 15 ids) — producing an evidence packet of about 15 signals under 8,000 tokens. That packet feeds the single model call, then a grounding gate strips any cited id that does not resolve, yielding an incident report of ranked causes with checkable citations.",
      },
      {
        url: "/projects/replay/narrow.webp",
        caption: "Blast radius: what the failure could have touched",
        alt: "Diagram titled 'Narrow — the blast radius'. Trace spans from Tempo listing calls such as web to checkout and checkout to payments are turned into a service call graph. The alerted service, web, is highlighted, and a breadth-first walk expands through checkout, payments, inventory and db to produce a blast radius of size 5.",
      },
      {
        url: "/projects/replay/when.webp",
        caption: "Change-point detection: when it started",
        alt: "Diagram titled 'When — when did it actually start?'. A latency chart shows a flat baseline over its first third, then a step change; the detector walks back from the alarm to the last empty bucket to mark onset. Below it a CUSUM score chart crosses a threshold of 5 for three sustained samples. A side panel lists the control-chart parameters, with sigma estimated from median absolute deviation rather than the mean.",
      },
      {
        url: "/projects/replay/suspects.webp",
        caption: "Correlating suspect change events",
        alt: "Diagram titled 'Suspects — which change explains that moment?'. A timeline marks a causal window before the inflection point, with a 120-second grace band after it; a rollback landing after the inflection is excluded as a response rather than a cause. One panel breaks the score into weighted proximity, scope and corroboration terms, and another shows the resulting ranked candidates, with a deploy 90 seconds before the inflection scoring highest.",
      },
      {
        url: "/projects/replay/gather.webp",
        caption: "Packing the evidence packet",
        alt: "Diagram titled 'Gather — the only evidence the model ever sees'. Three steps: bounded retrieval reads a capped number of log lines from Loki once per suspect around the onset anchor; Drain-style templating collapses near-identical log lines into a single template with a count; and a slot budget keeps common and rare shapes under a token ceiling while reserving the top candidate signals from being cut. A footer lists the id prefixes every signal carries, which is what a model claim must cite.",
      },
      {
        url: "/projects/replay/reason.webp",
        caption: "Reasoning + the grounding gate",
        alt: "Diagram titled 'Reason — one model call'. The roughly 15-signal evidence packet becomes a prompt in which untrusted text is encoded at every boundary, goes to the model once, and the response passes through a grounding gate that checks whether each cited id actually resolves against the packet.",
      },
    ],
    highlights: [
      "Four deterministic stages compress ~2,000 log lines per suspect — a 10,000-line ceiling across a five-service blast radius — into a ~15-signal, under-8,000-token evidence packet before a single model call.",
      "A grounding gate drops any model claim whose citations aren't in that packet, so reports are 100% cited across 20/20 scenarios. CI fails the build below 100%.",
      "A fault-injection eval rig replays 20 injected outages: 5/5 top-3 on bad deploy, config drift and resource exhaustion; 3/5 on dependency failure.",
      "195 JUnit tests and 7 integration suites run against real Postgres and the telemetry stack via Testcontainers.",
    ],
    stack: [
      "Java 25",
      "Spring Boot 4.1",
      "Spring AI 2.0",
      "PostgreSQL 17",
      "Flyway",
      "React 19",
      "TypeScript",
      "OpenTelemetry",
      "Prometheus",
      "Docker",
      "Testcontainers",
      "GitHub Actions",
    ],
    status: "shipped",
    year: 2026,
    is_best: true,
    is_current: false,
    sort_order: 0,
  },
  {
    id: "10",
    name: "API Key & Quota Service (mint)",
    description:
      "A Go service that issues, validates, and meters API keys for backend services. Stateless replicas behind nginx, Redis for caching and token-bucket rate limiting, Postgres as source of truth, with the validate hot path tuned to keep Postgres out of it.",
    github_url: "https://github.com/Sashreek007/mint",
    demo_url: null,
    image_url: "/projects/mint/architecture.webp",
    video_url: null,
    gallery: [
      {
        url: "/projects/mint/grafana-overview.webp",
        caption: "Service dashboard under load",
        alt: "Grafana service dashboard for mint captured during a load test, showing request rate, latency percentiles, cache hit rate and error panels across the two keyservice replicas.",
      },
      {
        url: "/projects/mint/grafana-tenants.webp",
        caption: "Per-tenant quota and usage",
        alt: "Grafana per-tenant dashboard for mint, breaking request volume, quota consumption and rate-limit rejections out by individual tenant.",
      },
    ],
    highlights: [
      "A three-tier cache — in-process, then Redis, then Postgres — with pub/sub invalidation, holding a 99.7% hit rate.",
      "One atomic Lua script does the rate limit, quota check and metering in a single Redis round-trip.",
      "Redis counters plus a leader-lease batch flusher hold database writes to a load-invariant ~10 writes/s.",
      "Benchmarked with committed, reproducible load tests, Prometheus and Grafana dashboards, and integration tests against real Postgres and Redis via Testcontainers.",
    ],
    stack: [
      "Go",
      "Redis",
      "PostgreSQL",
      "Lua",
      "nginx",
      "Docker",
      "Prometheus",
      "Grafana",
      "Testcontainers",
    ],
    status: "shipped",
    year: 2026,
    is_best: true,
    is_current: false,
    sort_order: 1,
  },
  {
    id: "11",
    name: "Durable Execution Engine (Latch)",
    description:
      "A durable execution engine for AI agent workflows. A worker claims one step at a time under a lease, a model decides what happens next, and every decision is recorded as a durable fact the moment it is made — so a machine that dies mid-step recovers by reading facts forward instead of re-running work. Tool calls that spend money or can't be undone are gated behind a human approval. Currently in development.",
    github_url: null,
    demo_url: null,
    image_url: "/projects/latch/workflow-trace.webp",
    video_url: null,
    gallery: [
      {
        url: "/projects/latch/workflows.webp",
        caption: "UI prototype — workflow operations",
        alt: "Dark dashboard prototype titled 'Workflow operations'. Four counters across the top track active, ready, needs-review and recovered workflows. A live workflow table lists each run with its status, phase, step, spend and age, and a right-hand rail shows the selected workflow's definition, worker, lease token and event count, its latest checkpoint, and a panel showing the four invariants as verified. All values are sample data.",
      },
      {
        url: "/projects/latch/workflow-trace.webp",
        caption: "UI prototype — workflow trace",
        alt: "Dark dashboard prototype showing the trace of a single workflow as a chronological event timeline: a lease being claimed, a model decision recorded with its provider, token count and cost, an intent recorded with an idempotency key, a worker handover to a second worker, and a deduplicated outcome noting no second provider call. A right-hand rail breaks out the budget envelope, the lease with its heartbeat and fencing token, the model decision, and the effect guarantee. All values are sample data.",
      },
      {
        url: "/projects/latch/approvals.webp",
        caption: "UI prototype — approval queue",
        alt: "Dark dashboard prototype titled 'Approval queue', listing risk-gated actions awaiting a decision with their due times, customer and risk level. The detail pane shows ticket facts, a narrow audit timeline, and side-by-side proposer and critic panels in which one model recommends approving a refund and a second escalates it for manual review, each with its rationale and evidence. A footer notes the workflow is suspended holding rows only. All values are sample data.",
      },
      {
        url: "/projects/latch/invariants.webp",
        caption: "UI prototype — invariant sweep",
        alt: "Dark dashboard prototype titled 'Correctness verification'. Four cards show the invariants — no duplicate effects, no lost workflows, single owner, budget ceiling — each marked verified. Panels below report a seeded invariant sweep, the mechanism backing each invariant, recently failing fixtures that were fixed, and a crash-coverage list marking which points in the step loop have been exercised. All values are sample data.",
      },
      {
        url: "/projects/latch/cost-reliability.webp",
        caption: "UI prototype — cost and reliability",
        alt: "Dark dashboard prototype titled 'Cost & reliability'. Top cards track model spend, average spend per workflow, routing savings and budget breaches, with sparklines. Panels below break spend down by workflow phase and provider, compare routing strategies against their estimated spend, list recent recovery evidence, and show a budget envelope in which reserved plus spent stays within the ceiling. All values are sample data.",
      },
    ],
    highlights: [
      "Queue, events and state commit in one Postgres transaction, so there is no dual-write window where work is queued but the state never lands.",
      "Workers hold a lease with a fencing token, so a zombie that wakes up after its lease expired cannot write over the worker that replaced it.",
      "Idempotency keys name the logical effect rather than the attempt, so a retry after a crash settles the same effect instead of firing it a second time.",
      "Correctness is meant to be proven rather than asserted: the four invariants are pure functions run over the whole event log across seeded crash schedules.",
      "Cloud-native from the first week — ECS Fargate, RDS Postgres, SQS and Bedrock, defined in CDK and deployed by GitHub Actions over OIDC.",
    ],
    stack: [
      "TypeScript",
      "Node.js",
      "PostgreSQL 17",
      "AWS ECS Fargate",
      "Amazon SQS",
      "Amazon Bedrock",
      "OpenAI",
      "AWS CDK",
      "Docker",
      "GitHub Actions",
    ],
    status: "building",
    year: 2026,
    is_best: true,
    is_current: true,
    sort_order: 2,
  },
  {
    id: "1",
    name: "Career Co-Pilot",
    description:
      "AI-assisted job workflow platform that matches roles to your profile, generates tailored resumes, and supports browser-assisted applications while keeping the user in control.",
    github_url: "https://github.com/Sashreek007/career-savers_CareerCo-Pilot",
    demo_url: null,
    image_url: null,
    video_url: null,
    gallery: [],
    highlights: [],
    stack: ["React", "TypeScript", "FastAPI", "Python", "Playwright", "SQLite", "Gemini API"],
    status: "shipped",
    year: 2025,
    is_best: true,
    is_current: false,
    sort_order: 3,
  },
  {
    id: "2",
    name: "DoomScroller",
    description:
      "Chrome extension that converts doomscrolling into measurable distance, coins, and multiplayer battles with local-first tracking, Supabase sync, and personalized AI feedback.",
    github_url: "https://github.com/Sashreek007/Doom-Scroller-by-Commit-and-Pray",
    demo_url: null,
    image_url: null,
    video_url: null,
    gallery: [],
    highlights: [],
    stack: ["TypeScript", "React", "TailwindCSS", "Supabase", "PostgreSQL", "Chrome Extension"],
    status: "shipped",
    year: 2025,
    // Stays "best work" so it keeps its place on /work; ordered past the
    // homepage's four-item cut so it drops off the reel. is_best drives both
    // surfaces, so clearing it here would hide the project from /work too.
    is_best: true,
    is_current: false,
    sort_order: 4,
  },
  {
    id: "4",
    name: "FluxAtlas — Economic Trading Engine",
    description:
      "Full-stack auction simulation platform modeling international resource trading with Vickrey auction mechanisms across 50+ simulated countries.",
    github_url: "https://github.com/Aarushb/NH25_flux_Atlas",
    demo_url: null,
    image_url: null,
    video_url: null,
    gallery: [],
    highlights: [],
    stack: ["FastAPI", "React", "PostgreSQL", "Python", "TypeScript"],
    status: "shipped",
    year: 2025,
    is_best: true,
    is_current: false,
    sort_order: 5,
  },
  {
    id: "5",
    name: "Spam Detection Discord Bot",
    description:
      "Deployed scam detection bot that identifies and removes malicious messages in real time with low-latency inference.",
    github_url:
      "https://github.com/UndergraduateArtificialIntelligenceClub/Spam-Detection-Discord-Bot",
    demo_url: null,
    image_url: null,
    video_url: null,
    gallery: [],
    highlights: [],
    stack: ["Python", "Discord.py", "Hugging Face"],
    status: "active",
    year: 2025,
    is_best: true,
    is_current: false,
    sort_order: 6,
  },
  {
    id: "6",
    name: "Balloon Popper — Gesture-Controlled Game",
    description:
      "Gesture-controlled arcade game with webcam-based hand tracking at 60 FPS and dynamic difficulty scaling.",
    github_url: "https://github.com/Sashreek007/fruit-ninja-hand-tracker",
    demo_url: null,
    image_url: null,
    video_url: null,
    gallery: [],
    highlights: [],
    stack: ["Python", "MediaPipe", "Pygame", "OpenCV"],
    status: "shipped",
    year: 2024,
    is_best: true,
    is_current: false,
    sort_order: 7,
  },
  {
    id: "7",
    name: "LinkedIn Profile Summarizer",
    description:
      "Automated profile analysis pipeline combining web scraping and LLM processing to generate structured summaries.",
    github_url: "https://github.com/Sashreek007/Langchain_agent",
    demo_url: null,
    image_url: null,
    video_url: null,
    gallery: [],
    highlights: [],
    stack: ["Python", "LangChain", "OpenAI API"],
    status: "shipped",
    year: 2024,
    is_best: false,
    is_current: false,
    sort_order: 8,
  },
  {
    id: "8",
    name: "ClubMate AI",
    description:
      "Open-source automation platform for club operations, focused on intelligent task scheduling and document workflows.",
    github_url: "https://github.com/UndergraduateArtificialIntelligenceClub/Clubmate-AI",
    demo_url: null,
    image_url: "/projects/clubmate/ragbotv2.jpg",
    video_url: "/projects/clubmate/ragbotv2.mp4",
    gallery: [
      {
        url: "/projects/clubmate/ragbotv2.mp4",
        poster: "/projects/clubmate/ragbotv2.jpg",
        caption: "Knowledge base and question answering",
        alt: "Screen recording of a Discord server beside the ClubMate admin dashboard. The bot posts its command list, split into member commands and exec commands, while the dashboard's Knowledge Base panel shows the indexed document chunks and offers to sync a Google Doc or upload a file.",
      },
      {
        url: "/projects/clubmate/meetings.mp4",
        poster: "/projects/clubmate/meetings.jpg",
        caption: "Scheduling and rescheduling meetings",
        alt: "Screen recording in Discord: a slash command schedules a session, the bot replies with a Google Calendar link and invites an attendee, then a reschedule command finds two matching meetings and asks which event id to move.",
      },
      {
        url: "/projects/clubmate/meeting-transcription.mp4",
        poster: "/projects/clubmate/meeting-transcription.jpg",
        caption: "Recording, transcribing and summarising a meeting",
        alt: "Screen recording in Discord: the bot joins a voice lounge and starts recording, then on stop reports that it is transcribing and summarising, and posts a meeting summary with key discussion points, decisions made, action items, next steps and a full speaker-labelled transcript.",
      },
      {
        url: "/projects/clubmate/sheets.mp4",
        poster: "/projects/clubmate/sheets.jpg",
        caption: "Reading and summarising a spreadsheet",
        alt: "Screen recording in Discord: a read-sheet command returns a summary of a Google Sheet, listing row and column counts, completion and progress insights, due-date highlights, anomalies such as rows missing review dates, and a set of representative rows.",
      },
      {
        url: "/projects/clubmate/creating-forms.mp4",
        poster: "/projects/clubmate/creating-forms.jpg",
        caption: "Generating a Google Form",
        alt: "Screen recording showing a Google Form the bot generated — a sports survey with a name field, a multiple-choice question and a short-answer question — beside the ClubMate dashboard overview reporting the bot online, the Google account connected, and the indexed knowledge base.",
      },
      {
        url: "/projects/clubmate/roombooking.mp4",
        poster: "/projects/clubmate/roombooking.jpg",
        caption: "Library room availability",
        alt: "Screen recording in Discord: the bot answers a room-availability request with a dated list of study rooms and their free time slots, a total slot count, and a link out to the library's booking page.",
      },
      {
        url: "/projects/clubmate/events.mp4",
        poster: "/projects/clubmate/events.jpg",
        caption: "Upcoming events",
        alt: "Screen recording in Discord: an events command lists what is coming up, with the bot's full command reference visible above it and a scheduled project showcase entry with its time range below.",
      },
    ],
    highlights: [],
    stack: ["Python", "LangChain", "LangGraph", "MCP", "Discord.py", "Gemini", "Google Workspace API"],
    status: "building",
    year: 2025,
    is_best: false,
    is_current: true,
    sort_order: 9,
  },
];

export function projectSlug(p: Project) {
  return slugify(p.name);
}

export function projectHref(p: Project) {
  return `/projects/${p.id}`;
}
