// Generated by scripts/blender/make-sprite-sheet.py — do not edit.
// Regenerate after re-rendering the Blender frames.
export const ASTEROID_SPRITE = {
  "frames": 48,
  "cols": 8,
  "rows": 6,
  "cellW": 506,
  "cellH": 615,
  "sheetW": 4048,
  "sheetH": 3690
} as const;
