// Generated by scripts/blender/make-sprite-sheet.py — do not edit.
// Regenerate after re-rendering the Blender frames.
export const ASTEROID_SPRITE = {
  "frames": 36,
  "cols": 6,
  "rows": 6,
  "cellW": 308,
  "cellH": 324,
  "sheetW": 1848,
  "sheetH": 1944
} as const;
