// Generated by scripts/blender/make-sprite-sheet.py — do not edit.
// Regenerate after re-rendering the Blender frames.
export const ASTEROID_SPRITE = {
  "frames": 24,
  "cols": 6,
  "rows": 4,
  "cellW": 660,
  "cellH": 693,
  "sheetW": 3960,
  "sheetH": 2772
} as const;
